services:
  web:
    build: .
    container_name: php-nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      - frontend
    networks:
      - network

  db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: test0225
      POSTGRES_USER: test0225
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - network

  frontend:
    image: node:20
    container_name: vue-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  postgres_data:
